version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
  db: 
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fpoly
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - mysl_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db

  composer:
    image: composer
    volumes:
      - ./:/app
    working_dir: /app
  
      
    
volumes:
  mysl_data:

